export enum BasicRelation {
    TREE_NODE_FATHER = "FATHER",
    TREE_NODE_MOTHER = "MOTHER",
    TREE_NODE_WIFE = "WIFE",
    TREE_NODE_HUSBAND = "HUSBAND",
    TREE_NODE_SISTER = "SISTER",
    TREE_NODE_BROTHER = "BROTHER",
    TREE_NODE_SON = "SON",
    TREE_NODE_DAUGHTER = "DAUGHTER"
}